#!groovy

// Generated by IBM TransformationAdvisor
// Sun Jul 21 11:01:26 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}